# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lead.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lead.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlead.proto\x12\x04lead\"5\n\x08LeadData\x12\x14\n\x0c\x63lient_email\x18\x01 \x01(\t\x12\x13\n\x0b\x66inal_price\x18\x02 \x01(\x01\"\x18\n\x08PdfReply\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2m\n\x0bLeadService\x12/\n\x10SendNotification\x12\x0e.lead.LeadData\x1a\x0b.lead.Empty\x12-\n\x0bGeneratePdf\x12\x0e.lead.LeadData\x1a\x0e.lead.PdfReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lead_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEADDATA']._serialized_start=20
  _globals['_LEADDATA']._serialized_end=73
  _globals['_PDFREPLY']._serialized_start=75
  _globals['_PDFREPLY']._serialized_end=99
  _globals['_EMPTY']._serialized_start=101
  _globals['_EMPTY']._serialized_end=108
  _globals['_LEADSERVICE']._serialized_start=110
  _globals['_LEADSERVICE']._serialized_end=219
# @@protoc_insertion_point(module_scope)
