# frontend/Dockerfile.dev

FROM node:20-alpine

WORKDIR /app

# Копируем package.json и package-lock.json (если есть)
COPY frontend/package*.json ./
RUN npm install

# Копируем остальные файлы фронтенда
COPY frontend/ .

EXPOSE 5173

# Запускаем Vite в режиме разработки на всех интерфейсах
CMD ["npm", "run", "dev", "--", "--host"]
