# docker-compose.yml (ИСПРАВЛЕННАЯ ВЕРСИЯ)

services:
  db:
    image: postgres:15-alpine
    container_name: leadconverter-pro-db-1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h ${DB_HOST} -p ${DB_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: leadconverter-pro-backend-1
    command: uvicorn main:app --uds /tmp/uvicorn.sock --reload
    volumes:
      - ./app:/app
      - uvicorn-sock:/tmp
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  frontend:
    build:
      # --- ИЗМЕНЕНИЯ ЗДЕСЬ ---
      context: .  # 1. Контекст теперь - корень проекта.
      dockerfile: frontend/Dockerfile.dev # 2. Путь к Dockerfile указываем от корня.
      # --- КОНЕЦ ИЗМЕНЕНИЙ ---
    container_name: leadconverter-pro-frontend-1
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  postgres_data:
  uvicorn-sock: