services:
  db:
    image: postgres:15-alpine
    container_name: leadconverter-pro-db-1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: leadconverter-pro-backend:dev   # используем уже собранный образ
    container_name: leadconverter-pro-backend-1
    working_dir: /app/backend
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app


  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
      container_name: leadconverter-pro-frontend-1
      ports: ["5173:5173"]
      environment:
       - VITE_API_BASE_URL=http://backend:8000
      depends_on: [backend]

volumes:
  postgres_data:
