version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: leadconverter-pro-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .              # Сборка из корня проекта
      dockerfile: backend/Dockerfile
    container_name: leadconverter-pro-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app        # Монтируем исходники для hot‑reload
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  frontend:
    build:
      context: .              # Контекст корня проекта
      dockerfile: frontend/Dockerfile.dev
    container_name: leadconverter-pro-frontend
    volumes:
      - ./frontend:/app       # Монтируем исходники для hot‑reload
      - /app/node_modules     # Предотвращаем перезапись node_modules на хосте
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://backend:8000

volumes:
  postgres_data:
