# docker-compose.override.yml
services:
  backend:
    environment:
      PYTHONPATH: /app/backend
    command: ["/bin/sh","-lc","cd /app/backend && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]
